# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BabyBundle' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BabyBundle

pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'GoogleSignIn'
pod 'FirebaseUI/Google'
pod 'Firebase/Storage'

end
